# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Login_Dialog(object):
    # A function that receives  a Dialog, client, main_win. The function builds the dialog with its details
    def setupUi(self, Dialog, client, main_win):
        Dialog.setObjectName("Dialog")
        Dialog.resize(353, 313)
        Dialog.setFixedSize(353, 313)
        Dialog.setStyleSheet("background-color: rgb(54, 54, 54);")
        Dialog.setModal(True)
        self.sign_in_btn = QtWidgets.QPushButton(Dialog)
        self.sign_in_btn.setGeometry(QtCore.QRect(110, 260, 130, 37))
        self.sign_in_btn.setStyleSheet("background-color: rgb(14, 154, 175);\n"
"color: rgb(255,255,255);\n"
"font-size: 18pt\n"
"")
        self.sign_in_btn.setObjectName("pushButton_3")
        self.username_text = QtWidgets.QLabel(Dialog)
        self.username_text.setGeometry(QtCore.QRect(30, 90, 111, 21))
        self.username_text.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 16pt")
        self.username_text.setObjectName("label_4")
        self.lineEdit_username = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_username.setGeometry(QtCore.QRect(30, 120, 291, 31))
        self.lineEdit_username.setAutoFillBackground(False)
        self.lineEdit_username.setStyleSheet("background-color: rgb(197,197,197);\n"
"color: rgb(42, 42, 42);\n"
"font-size: 12pt\n"
"")
        self.lineEdit_username.setText("")
        self.lineEdit_username.setPlaceholderText("")
        self.lineEdit_username.setObjectName("lineEdit_5")
        self.heading_text = QtWidgets.QLabel(Dialog)
        self.heading_text.setGeometry(QtCore.QRect(30, 10, 221, 71))
        self.heading_text.setStyleSheet("background-color: rgb(54,54,54);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 28pt \"MS Shell Dlg 2\";")
        self.heading_text.setObjectName("label_3")
        self.lineEdit_password = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_password.setGeometry(QtCore.QRect(30, 190, 291, 31))
        self.lineEdit_password.setAutoFillBackground(False)
        self.lineEdit_password.setStyleSheet("background-color: rgb(197,197,197);\n"
"color: rgb(42, 42, 42);\n"
"font-size: 12pt")
        self.lineEdit_password.setInputMethodHints(QtCore.Qt.ImhHiddenText | QtCore.Qt.ImhNoAutoUppercase | QtCore.Qt.ImhNoPredictiveText | QtCore.Qt.ImhSensitiveData)
        self.lineEdit_password.setInputMask("")
        self.lineEdit_password.setText("")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setPlaceholderText("")
        self.lineEdit_password.setObjectName("lineEdit_6")
        self.password_text = QtWidgets.QLabel(Dialog)
        self.password_text.setGeometry(QtCore.QRect(30, 160, 111, 21))
        self.password_text.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 16pt")
        self.password_text.setObjectName("label_5")
        self.invaild_details_text = QtWidgets.QLabel(Dialog)
        self.invaild_details_text.setGeometry(QtCore.QRect(30, 230, 221, 21))
        self.invaild_details_text.setStyleSheet("background-color: rgb(54,54,54);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.invaild_details_text.setObjectName("label_6")
        self.fill_fields_text = QtWidgets.QLabel(Dialog)
        self.fill_fields_text.setGeometry(QtCore.QRect(30, 230, 221, 21))
        self.fill_fields_text.setStyleSheet("background-color: rgb(54,54,54);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.fill_fields_text.setObjectName("label_11")

        self.invaild_details_text.hide()
        self.fill_fields_text.hide()
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.sign_in_btn.clicked.connect(lambda: self.try_login(Dialog, client, main_win))

    # A function that receives Dialog, client, main_win. The function gets the fields from the lines, does a validation, and send the details of the user to the server to check if the details are correct. The function would raise error labels when necessary
    def try_login(self, Dialog, client, main_win):
        username = self.lineEdit_username.text()
        password = self.lineEdit_password.text()

        if main_win.the_app_config.is_using_debug_values():
            username = main_win.the_app_config.get_user_name()
            password = main_win.the_app_config.get_password()

        if username == '' or password == '':
            self.fill_fields_text.show()
            self.fill_fields_text.raise_()
            return
        res = client.login(username, password)
        if res != None:
            main_win.turn_into_logged_in_mode(username, res)
            main_win.fill_table(client)
            Dialog.close()
        else:
            self.invaild_details_text.show()
            self.invaild_details_text.raise_()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.sign_in_btn.setText(_translate("Dialog", "Sign in"))
        self.username_text.setText(_translate("Dialog", "Username:"))
        self.heading_text.setText(_translate("Dialog", "Login"))
        self.password_text.setText(_translate("Dialog", "Password:"))
        self.invaild_details_text.setText(_translate("Dialog", "invalid username or password !"))
        self.fill_fields_text.setText(_translate("Dialog", "please fill all the fields!"))
